# Generated by Django 4.2.6 on 2023-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
