# Generated by Django 4.2.6 on 2023-10-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_sellerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
